/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
    uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
    uint32_t *pPortAOutputReg = (uint32_t*)0x40020014;
    uint32_t *pPortAInputReg = (uint32_t*)0x40020010;


    *pClkCtrlReg |= 0x01;

    *pPortAModeReg &= 0xFFFFF3FF;
    *pPortAModeReg |= 0x00000400;



    while(1){
		uint32_t pinStatus = (uint32_t)(*pPortAInputReg & 0x1);

		if(pinStatus){
 			*pPortAOutputReg |= 0x0020;
		}else{
			*pPortAOutputReg &= ~(0x0020);
		}
    }

}
